import StreamVideoProvider from '@/providers/streamClientProvider';
import type { Metadata } from "next";
import React from 'react';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout = ({ children }: { children: React.ReactNode }) => {

  return (
    <main>
      <StreamVideoProvider>
        {children}
      </StreamVideoProvider>
    </main>
  )
}
export default RootLayout

