import {
  ClerkProvider
} from '@clerk/nextjs';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const bodyClass = `${inter.className} bg-dark-2`;


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={bodyClass}>
        <ClerkProvider>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}

// layout.tsx defines the global layout for all pages in the Next.js app.
// It is a Server Component by default and runs on the server, unless you explicitly mark it with "use client" at the top.
// It wraps all page.tsx files in the route and renders them via the `children` prop.
// Use this to define shared structure like <html>, <body>, fonts, global styles, navbars, etc.

